baseURL = 'https://blog.hicky.top'
languageCode = 'zh-cn'
title = 'Corn çš„è‡ªç•™åœ°'
theme = 'hugo-theme-stack'

[markup]
  [markup.highlight]
    noClasses = false # ä»£ç å—å¯ä»¥è¢«æ·±è‰²æµ…è‰²æ”¹å˜æ ·å¼
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[params]
  mainSections = ["posts"] # ä¸»é¡µé¢ä¸»å—
  
  [params.widgets]
    homepage = [ # ä¸»é¡µé¢çš„å…¶å®ƒç»„ä»¶
      { type = "search" },
      { type = "archives", params = { limit = 10 } },
      { type = "categories", params = { limit = 10 } },
      { type = "tag-cloud", params = { limit = 10 } }
    ]
    page = [
      { type = "toc" }
    ]

  [params.article]
    toc = true # æ–‡ç« ç›®å½•

  [params.comments]
    enabled = true
    provider = "utterances"

    [params.comments.utterances]
      repo = "hi-cky/blog-comments"  # ä½¿ç”¨ä½ çš„GitHubä»“åº“
      issueTerm = "pathname"
      label = "ğŸ’¬è¯„è®º"

  math = true # å¯åŠ¨æ•°å­¦å…¬å¼æ”¯æŒ